### ISSUE TITLE
Optional archive feature for private accounts

### ISSUE THREAD

**Issue by erdihu** [jonschoning/espial#10]
There is an option to enable link archiving for added bookmarks but it is only valid if the account is public. As a private account holder, I'd like to be able to archive the links I want whether I am using a public or a private account.

Possible solutions:
- The archive option could be changed so that it can process all the links.
- Add URL page can have a new option to override global archive settings.

**Comment by jonschoning** [comment]
- Changed archive behavior so that when enbaled it is active for private accounts 
- updated espial-docker to latest

**Comment by erdihu** [comment]
Great, thank you!
