### ISSUE TITLE
Integrate into existing server

### ISSUE THREAD

**Issue by gDanix** [jonschoning/espial#17]
Would it be very difficult to change the configuration (hopefully, only Yesod configuration) so to have this program running with an existing PostgreSQL instance, instead of the sqlite backend it uses by default?.

Also I would like to be able to use it through CGI with Apache.

I'm a newbie in Haskell, but I would like to contribute some code in this direction, but I think I'm going to need help.

Thank you!

**Comment by jonschoning** [comment]
Having some kind of build flag that selects sqlite or postgres might be something i'd consider in the future, but it would involve adding CPP preprocessor directives to switch between the sqlite and postgres methods for several files and so i would consider this out of scope at this time, unless more people asked for it.

If you're curious, if you do 
`stack new sqlite yesodweb/sqlite`
`stack new postgres yesodweb/postgres`
you can see roughly what would need to change from base yesod, and then Additionally, theres also stuff in `app/migration` and replacing `sqlite_group_concat`'s `GROUP_CONCAT` in `Model.hs` with `STRING_AGG` 

It might be a bit much to bite off as a new learner, though.

**Comment by gDanix** [comment]
I'm so sorry, I missed the notification email about your reply. Thank you for your quick response.

> it would involve adding CPP preprocessor directives to switch between the sqlite and postgres methods
I assumed Yesod could abstract and provide a common interface for all of the supported databases. My bad!

> so i would consider this out of scope at this time
Would you be willing to review and guide me in the making of a PR? I also understand that this will require an extra work from your side, and if you prefer to focus on somewhere else, it's fine, of course.

I'm going to install this software anyway. I really need to put my links in order, and being wrote in Haskell is and ideological plus for me.

Thank you!
