### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by grtcdr** [jonschoning/espial#26]
Are there plans to document some of the common operations? 

For example: for someone like me, who's never used Haskell before, how do I close the network socket that was opened when I ran `espial`?

Is there a help section that I'm missing?

**Comment by jonschoning** [comment]
shouldn't the network socket automatically close when you stop the application? 

theres also espial-docker if you just want to run a conatiner.

**Comment by grtcdr** [comment]
> shouldn't the network socket automatically close when you stop the application?

Unfortunately, it did not...

**Comment by jonschoning** [comment]
What command are you using to run it?

**Comment by grtcdr** [comment]
`stack exec espial -- +RTS -T` as the README states to run a production server.

**Comment by jonschoning** [comment]
i would be surprised if the socket was owned by espial and still listening after the process was shutdown.  you can run
`while true; do sudo netstat -plat | grep 3000; echo ''; sleep 1; done`
to see the owning process and the socket state

**Comment by grtcdr** [comment]
I might've done something wrong along the way then...

**Comment by grtcdr** [comment]
Feel free to close this :)
