### ISSUE TITLE
automatically bookmark pages annotated with hypothes

### ISSUE THREAD

**Issue by boehs** [jonschoning/espial#39]
Is there interest in implementing this or how would I do it with cron etc?

**Comment by jonschoning** [comment]
not sure i understand the use-case if you're already using hypothesis for bookmarking the web.

**Comment by boehs** [comment]
> not sure i understand the use-case if you're already using hypothesis for bookmarking the web. FWIW you can add bookmarks programatically with api key auth #35

hypothes is not a bookmarker, it is a web annotator. You can not "bookmark" a page without annotating it. I would like to have a collection of all my important pages, both just bookmarks (via espial) and pages with annotations (via hypothes)
