### ISSUE TITLE
Is it really safe to recommend this?

### ISSUE THREAD

**Issue by ekianjo** [jonschoning/espial#4]
I saw that the first line of the installation guide is:

curl -sSL https://get.haskellstack.org/ | sh

It's probably not a good idea to recommend executing a remote shell script without verifying its contents in any way. Or am I too paranoid?

**Comment by jonschoning** [comment]
this used to be the easiest way to install stack, but i'll update the readme to just point to the stack page.

**Comment by ekianjo** [comment]
Thanks, its probably better this way.

**Comment by brettinternet** [comment]
@ekianjo You may also consider the docker way via [espial-docker](https://github.com/jonschoning/espial-docker). A compose file with a reverse proxy like traefik is very easy to deploy. [Here's mine](https://github.com/brettinternet/homelab/blob/master/compose/espial.yml).
