### ISSUE TITLE
Question: Import with Archive

### ISSUE THREAD

**Issue by nershman** [jonschoning/espial#42]
Is it possible to import existing archived sites along with bookmarks JSON using this tool?

Thanks,
Sherman

**Comment by jonschoning** [comment]
Currnetly, if you use JSON-based [Pinboard import format](https://github.com/jonschoning/espial#import-bookmark-file-format-pinboard-compatible-format) , you can also give each bookmark a `"archive_url"` field which points to the url where the bookmark is archived.   Then the green archive box next to each bookmark will point to that bookmark's `"archive_url"`

**Comment by nershman** [comment]
Awesome, thanks!
