### ISSUE TITLE
RSS feed always proposes all content instead of tags in use

### ISSUE THREAD

**Issue by MagicFab** [jonschoning/espial#43]
When looking at a list of links resulting from combined or single tags, the RSS feed proposed is always for all the content, not the search result.

For example for https://esp.ae8.org/u:demo/t:test+tag the RSS feed is proposing https://esp.ae8.org/u:demo/feed.xml

It would be useful to be able to have RSS feeds per tag or per tag combinations.

**Comment by jonschoning** [comment]
This feature has been committed to master.  

Note that while RSS feeds based on search queries will work anonymously, RSS feeds based on filters (e.g. private/starred etc...) will only be accurate if the client is logged in via an authentication cookie, which mirrors what an anonymous user would see when visiting a user's bookmarks.
