### ISSUE TITLE
Add SIGTERM handler to shut down cleanly

### ISSUE THREAD

**Issue by squires** [jonschoning/espial#46]
At a minimum, shouldn't the sqlite database be closed before terminating the process?

I have not touched Haskell in 15 years, so I wasn't sure if perhaps the framework was doing this. But the espial process does not even catch SIGTERM. So I'm assuming there's no shutdown code.

Checking to see if the process has registered a SIGTERM handler (reading /proc/[pid]/status for the SigCgt bitmap, where SIGTERM is signal 15, 1-based index):

```
ps aux | grep "[e]spial" | awk '{print $2}' | xargs -I{} grep SigCgt /proc/{}/status | awk '{print $2}' | xargs -I{} bash -c 'echo "$(((0x$1 >> 14) & 1))"' -- {}
```

There is a secondary problem with the docker configuration, where when shutting down the container SIGTERM will not reach espial (even after a signal handler is added). The way CMD is used executes espial under a shell. The shell is PID 1, and PID 1 does not have default signal handlers, so the signal just disappears. Changing from `CMD ./espial +RTS -T` to `CMD ["./espial", "+RTS", "-T"]` would cause espial to run as PID 1 instead of a shell, and be able to receive signals. (https://docs.docker.com/engine/reference/builder/#understand-how-cmd-and-entrypoint-interact)

**Comment by jonschoning** [comment]
I believe a SIGTERM handler can be added & the docker updates made, yes.

**Comment by jonschoning** [comment]
fixed in https://github.com/jonschoning/espial/pull/47

**Comment by squires** [comment]
It's working for me. Thanks!
