### ISSUE TITLE
A new Hackage release

### ISSUE THREAD

**Issue by dalpd** [jonschoning/espial#49]
Hi there!

I was trying to get Espial to build again on nixpkgs earlier and realized the release being tracked was of version 0.0.11.

Can we get a new release with the latest changes on Hackage?

**Comment by jonschoning** [comment]
sure

**Comment by jonschoning** [comment]
updated https://hackage.haskell.org/package/espial

**Comment by dalpd** [comment]
@jonschoning Could I bother you for another release? `connections` will get broken on nixpkgs soon so would be great to go 0.0.19.

**Comment by jonschoning** [comment]
updated https://hackage.haskell.org/package/espial-0.0.19

**Comment by jonschoning** [comment]
@dalpd  since 0.0.19 had issues with cabal deps, I added https://hackage.haskell.org/package/espial-0.0.20
