### ISSUE TITLE
Public vs Private

### ISSUE THREAD

**Issue by JeffCrum1** [jonschoning/espial#50]
First, let me say that I love the simplistic nature of this project and the bookmark page.

But, I think I may not be understanding what public and private are intended to be used for on both bookmarks and notes.

What I was thinking I could do is self host this using separate logins for my family.  But, I was expecting to be able to use the public vs private fields to allow each member to keep their privacy along with being able to share some items too.

For example, my wife and I both use the same banking bookmarks.  But, I have my own forums that she has zero interest in (F150Gen14 for example).  She has the same.  And, she is not as technical as I am.

So, I figured I could add all of our banking links as public and my own form links as private.  Then, expected for her to login and see the 'public' bookmarks I have added.

But, when she logs in, she doesn't see any of the 'public' bookmarks I have added.

Am I misunderstanding the intention of this?  Or, is it just not working?  And, not just the bookmarks.  But, the notes too.

And, what does Privacy Lockout (Private Account) mean in settings?

Thanks again!

**Comment by jonschoning** [comment]
if `Privacy Lock (Private Account)` is enabled, no one should be able to view any of your espial data except you (i.e. the owner of the user account), regardless of the private/public setting on the note or bookmark.

Assuming `Privacy Lock` is disabled, a `public` bookmark or note can be seen by someone who is either not logged in or is logged in as another user.  However your public items won't just appear in their home view.  They would need to navigate to the desired user's bookmark or notes page to see their public bookmarks or notes.  for example, you navigate to https://esp.ae8.org/u:demo to see the demo user's public bookmarks without being logged in, or navigate to https://esp.ae8.org/u:demo/notes to see the demo user's public notes without being logged in.   the `u:demo` in the url specifies which user's bookmarks you're viewing.

**Comment by JeffCrum1** [comment]
Okay.  Lemme see what I can see using this info.  Thanks for the explanation!
