### ISSUE TITLE
Ability to fetch the title of the link.

### ISSUE THREAD

**Issue by lexffe** [jonschoning/espial#8]
Instead of `[no title]`, there could be a button for users to fetch the title from the `<title>` tag of the website.

**Comment by jonschoning** [comment]
This is why I recommended to use the bookmarklet, which does populate the title.

But yes, perhaps there could be an option to populate the title if not using the bookmarklet as well

**Comment by jonschoning** [comment]
resolved by 7683c34

**Comment by jonschoning** [comment]
### inline bookmark editing
![image](https://user-images.githubusercontent.com/137183/72673315-30366800-3a2e-11ea-8adb-047b698e31e9.png)

### add new url page/popup
![image](https://user-images.githubusercontent.com/137183/72673322-4ba17300-3a2e-11ea-8c1f-831e628266fb.png)

**Comment by jonschoning** [comment]
fyi @gregf

**Comment by gregf** [comment]
@jonschoning ty
